### ISSUE TITLE
Release luna-soc 0.3.0

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/luna-soc#31]
This is the tracking issue for the luna-soc 0.2.0 release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
```

```[tasklist]
### Issues
- [ ] https://github.com/greatscottgadgets/luna-soc/issues/17
- [ ] https://github.com/greatscottgadgets/luna-soc/issues/21
- [ ] https://github.com/greatscottgadgets/luna-soc/issues/22
- [ ] https://github.com/greatscottgadgets/luna-soc/issues/23
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/luna-soc/pull/33
```

**Comment by antoinevg** [comment]
Completed: https://github.com/greatscottgadgets/luna-soc/releases/tag/0.3.1
